_call_function(_LZTAPI.__Threads.__Contests.create, {
    prize_type: (<%= prize_type %>),
    require_like_count: (<%= require_like_count %>),
    require_total_like_count: (<%= require_total_like_count %>),
    length_value: (<%= length_value %>),
    length_option: (<%= length_option %>),
    count_winners: (<%= count_winners %>),
    prize_data_money: (<%= prize_data_money %>),
    is_money_places: (<%= is_money_places %>),
    prize_data_places: (<%= prize_data_places %>),
    prize_data_upgrade: (<%= prize_data_upgrade %>),
    secret_answer: (<%= secret_answer %>),
    post_body:  (<%= post_body %>),
    title:  (<%= title %>),
    title_en:  (<%= title_en %>),
    tags:  (<%= tags %>),
    hide_contacts:  (<%= hide_contacts %>),
    allow_ask_hidden_content:  (<%= allow_ask_hidden_content %>),
    reply_group:  (<%= reply_group %>),
    comment_ignore_group:  (<%= comment_ignore_group %>),
    dont_alert_followers:  (<%= dont_alert_followers %>),
    watch_thread_state:  (<%= watch_thread_state %>),
    watch_thread:  (<%= watch_thread %>),
    watch_thread_email:  (<%= watch_thread_email %>),
    timeout:  (<%= timeout %>) * 1000,
    interval: (<%= interval %>) * 1000,
    maxTime: (<%= maxTime %>) * 1000
})!
<%= variable %> = _result_function()